site_name: Javier Egea Blasco

site_url: https://javieregeablasco.github.io/Apuntes

theme:
  language: es
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
#    - navigation.footer #añade flechas de navegacion en el footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

  logo: assets/mre.png
  favicon: assets/favicon.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference   

plugins:
  - search
  - tags
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true    
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables        

nav: 
  - Aplicaciones Ofimáticas: 
    - Presentación módulo: SMX/SMX_1/AO/00_Temario.md
    - UT 1 : SMX/SMX_1/AO/01_Instalacion de aplicaciones ofimaticas.md
    - UT 2 - Procesadores de texto:
      - UT 21 - Características de los procesadores de texto: SMX/SMX_1/AO/02_Procesadores_de_texto/021_Procesadores_de_texto.md
      - UT 22 - Instalación de LibreOffice Writer: SMX/SMX_1/AO/02_Procesadores_de_texto/022_LibreOffice_Writer_Instalacion.md
      - UT 23 - LibreOffice Writer: SMX/SMX_1/AO/02_Procesadores_de_texto/023_LibreOffice_Writer.md
                                                  
  - Programación en Python: 
    - Presentación módulo: SMX/SMX_2/Opt_Python/00_Temario.md
    - UT 1 Introducción a la programación : SMX/SMX_2/Opt_Python/01_Introduccion_a_la_programacion.md
    - UT 2 Python, instalación y IDE: SMX/SMX_2/Opt_Python/02_Python_Presentacion.md
    - UT 3 Elementos básicos de Python: SMX/SMX_2/Opt_Python/03_Python_Basico.md
  # - Code docs:
  #   - Java: ruta/archivo.md

  - Cloud Computing:
    - Presentación módulo: DAW/DAW_2/AWS/UT. 0-Temario.md
    - UT 1 Introducción al Cloud Computing: DAW/DAW_2/AWS/UT. 1-Introduccion.md
    - UT 2 AWS - Amazon Web Services: DAW/DAW_2/AWS/UT. 2-AWS.md



extra: 
    generator: false #eliminar el made with""
#   social: #sirve para añadir enlaces a RRSS
#     - icon: simple/youtube
#       link: https://youtube.com
#     - icon: simple/youtube
#       link: https://youtube.com
    
extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 - Javier Egea Blasco     