AWSTemplateFormatVersion: "2010-09-09"
Description: >
    Plantilla de ejemplo que despliega una instancia EC2 básica
    y muestra su IP pública como salida.

Parameters:
    InstanceType:
        Type: String
        Default: t2.micro
        Description: Tipo de instancia EC2
        AllowedValues:
          - t2.micro
          - t2.small

Mappings:
  RegionMap:
    eu-west-1:
      AMI: ami-0a8e758f5e873d1c1
    us-east-1:
      AMI: ami-0c02fb55956c7d316

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap
        - RegionMap
        - !Ref "AWS::Region"
        - AMI
      Tags:
        - Key: Name
          Value: ServidorWebEjemplo

Outputs:
  InstanceId:
    Description: ID de la instancia EC2
    Value: !Ref WebServer

  PublicIP:
    Description: Dirección IP pública de la instancia
    Value: !GetAtt WebServer.PublicIp