services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    restart: always

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: javier
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: MiBBDD

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: